#import <IJKMediaPlayer/IJKMediaPlayback.h>
#import <IJKMediaPlayer/IJKMPMoviePlayerController.h>
#import <IJKMediaPlayer/IJKFFOptions.h>
#import <IJKMediaPlayer/IJKFFMoviePlayerController.h>
#import <IJKMediaPlayer/IJKAVMoviePlayerController.h>
#import <IJKMediaPlayer/IJKMediaModule.h>
#import <IJKMediaPlayer/IJKMediaPlayer.h>
#import <IJKMediaPlayer/IJKNotificationManager.h>
#import <IJKMediaPlayer/IJKKVOController.h>

// backward compatible for old names
#define IJKMediaPlaybackIsPreparedToPlayDidChangeNotification IJKMPMediaPlaybackIsPreparedToPlayDidChangeNotification
#define IJKMoviePlayerLoadStateDidChangeNotification IJKMPMoviePlayerLoadStateDidChangeNotification
#define IJKMoviePlayerPlaybackDidFinishNotification IJKMPMoviePlayerPlaybackDidFinishNotification
#define IJKMoviePlayerPlaybackDidFinishReasonUserInfoKey IJKMPMoviePlayerPlaybackDidFinishReasonUserInfoKey
#define IJKMoviePlayerPlaybackStateDidChangeNotification IJKMPMoviePlayerPlaybackStateDidChangeNotification
#define IJKMoviePlayerIsAirPlayVideoActiveDidChangeNotification IJKMPMoviePlayerIsAirPlayVideoActiveDidChangeNotification
#define IJKMoviePlayerVideoDecoderOpenNotification IJKMPMoviePlayerVideoDecoderOpenNotification
#define IJKMoviePlayerFirstVideoFrameRenderedNotification IJKMPMoviePlayerFirstVideoFrameRenderedNotification
#define IJKMoviePlayerFirstAudioFrameRenderedNotification IJKMPMoviePlayerFirstAudioFrameRenderedNotification
